### ISSUE TITLE
update dependency for newer libdisplay-info possibe?

### ISSUE THREAD

**Issue by chrisco23** [rywng/wlroots-nvidia#1]
I haven't been able to update libdisplay-info for 2-3 weeks.

Is it possible wlroots-nvidia's dependency can be updated ?

```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libdisplay-info (0.2.0-1) breaks dependency 'libdisplay-info.so=1-64' required by wlroots-nvidia
```

**Comment by rywng** [comment]
Hello,
Unfortunately, this fork is unmaintained (I forgot about its existence).

You might find some useful information here:
https://aur.archlinux.org/packages/wlroots-nvidia
